NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.WARNING_YEARS = 10
NDefines.NDiplomacy.COALITION_YEARS = 10
NDefines.NDiplomacy.GUARANTEE_YEARS = 10
NDefines.NDiplomacy.HRE_VOTE_ROYAL_MARRIAGE = 30
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 4

NDefines.NCountry.CONCENTRATE_DEVELOPMENT_COOLDOWN_DURATION = -1
NDefines.NCountry.GOLDEN_ERA_YEARS = 20
NDefines.NCountry.CORRUPTION_FROM_BANNERS = 3
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 30
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 0
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = -10
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 0
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 0
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 400
NDefines.NCountry.BASE_POSSIBLE_POLICIES = 4
NDefines.NCountry.BASE_FREE_POLICIES = 2
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 0.50
NDefines.NCountry.PIETY_INCREASE_AT_GOOD_WAR = 0
NDefines.NCountry.PIETY_DECREASE_AT_BAD_WAR = 0
NDefines.NCountry.NAT_FOCUS_YEARS = 10
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.PS_BUY_IDEA = 360
NDefines.NCountry.PS_MOVE_TRADE_PORT = 100
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_HARSH_TREATMENT_REDUCE = 50
NDefines.NCountry.PS_ADD_ACCEPTED_CULTURE = 80

NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 40
NDefines.NEconomy.ALLOW_DESTROY_MANUFACTORY = 1

NDefines.NMilitary.SLACKEN_AP_DROP = 0.20
NDefines.NMilitary.BANNER_MANPOWER_USAGE = 0.0
NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = 0.00
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 3
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 0
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 0.1
NDefines.NMilitary.BANNER_REINFORCE_SPEED = 0.25
NDefines.NMilitary.CAVALRY_SPEED = 0.8
NDefines.NMilitary.ARTILLERY_SPEED = 0.6
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.SUPERIORITY_WARGOAL_WARSCORE_THRESHOLD = 25
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 50

NDefines.NAI.MIN_SCORE_TO_CONCENTRATE_DEVELOPMENT = -1

NDefines.NReligion.KARMA_RESTORE_ON_RULER_DEATH = 50

NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0
NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0
NDefines.NGovernment.FREE_CONCENTRATE_DEVELOPMENT_OTHER_STATE_PROVINCES_PROPORTION = 0

NDefines.NGraphics.AGGRESSIVE_EXPANSION_RED_R = 1.0
NDefines.NGraphics.AGGRESSIVE_EXPANSION_RED_G = 0.1
NDefines.NGraphics.AGGRESSIVE_EXPANSION_RED_B = 0.0
NDefines.NGraphics.AGGRESSIVE_EXPANSION_RED_A = 1.0
NDefines.NGraphics.AGGRESSIVE_EXPANSION_AMBER_R = 1.0
NDefines.NGraphics.AGGRESSIVE_EXPANSION_AMBER_G = 0.2
NDefines.NGraphics.AGGRESSIVE_EXPANSION_AMBER_B = 0.0
NDefines.NGraphics.AGGRESSIVE_EXPANSION_AMBER_A = 0.7
NDefines.NGraphics.AGGRESSIVE_EXPANSION_GREEN_R = 1.0
NDefines.NGraphics.AGGRESSIVE_EXPANSION_GREEN_G = 0.2
NDefines.NGraphics.AGGRESSIVE_EXPANSION_GREEN_B = 0.0
NDefines.NGraphics.AGGRESSIVE_EXPANSION_GREEN_A = 0.4

